apiVersion: apps/v1
kind: Deployment
metadata:
  name: fitness-tracker-backend
  labels:
    app: fitness-tracker-backend
spec:
  replicas: 1
  selector:
    matchLabels:
      app: fitness-tracker-backend
  template:
    metadata:
      labels:
        app: fitness-tracker-backend
    spec:
      containers:
        - name: fitness-tracker-backend
          image: $CI_REGISTRY_IMAGE/backend:$CI_COMMIT_SHORT_SHA
          ports:
            - containerPort: 8080
          env:
            - name: SPRING_DATASOURCE_URL
              valueFrom:
                secretKeyRef:
                  name: cloudsql-secrets
                  key: spring.datasource.url
            - name: SPRING_DATASOURCE_USERNAME
              valueFrom:
                secretKeyRef:
                  name: cloudsql-secrets
                  key: spring.datasource.username
            - name: SPRING_DATASOURCE_PASSWORD
              valueFrom:
                secretKeyRef:
                  name: cloudsql-secrets
                  key: spring.datasource.password
---
apiVersion: v1
kind: Service
metadata:
  name: fitness-tracker-backend
spec:
  selector:
    app: fitness-tracker-backend
  ports:
    - protocol: TCP
      port: 80
      targetPort: 8080
  type: LoadBalancer
