apiVersion: apps/v1
kind: Deployment
metadata:
  name: fitness-tracker-frontend
  labels:
    app: fitness-tracker-frontend
spec:
  replicas: 1
  selector:
    matchLabels:
      app: fitness-tracker-frontend
  template:
    metadata:
      labels:
        app: fitness-tracker-frontend
    spec:
      containers:
        - name: fitness-tracker-frontend
          image: $CI_REGISTRY_IMAGE/frontend:$CI_COMMIT_SHORT_SHA
          ports:
            - containerPort: 80
---
apiVersion: v1
kind: Service
metadata:
  name: fitness-tracker-frontend
spec:
  selector:
    app: fitness-tracker-frontend
  ports:
    - protocol: TCP
      port: 80
      targetPort: 80
  type: LoadBalancer
